In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/peace/Documents/Github_Repos/DS_Traffic_Crash_Analytics_&_Safety_Intelligence_Platform/data/Traffic_CrashesData.csv")

In [3]:
df.head().T

,0,1,2,3,4
CRASH_RECORD_ID,000c4307d8e9b39075cffdd0aade3603e0f96f14e41da9...,027b0b4c21460d3441fd83929abb9673c6fc0c7d575675...,04d91dffc94f677358ca47056921ba5c4224320df27ed4...,0b5603954d84b7341c7cad4f570ea039e85919f3750ccb...,00bce77960c2faa2a8782a8cac1d6e5715802d6c072a08...
CRASH_DATE,01/14/2025 12:25:00 PM,05/23/2025 09:30:00 AM,04/05/2025 08:00:00 PM,05/23/2025 09:15:00 AM,01/14/2025 08:00:00 AM
POSTED_SPEED_LIMIT,30,30,30,30,30
TRAFFIC_CONTROL_DEVICE,TRAFFIC SIGNAL,STOP SIGN/FLASHER,NO CONTROLS,NO CONTROLS,TRAFFIC SIGNAL
DEVICE_CONDITION,FUNCTIONING PROPERLY,UNKNOWN,NO CONTROLS,NO CONTROLS,FUNCTIONING PROPERLY
WEATHER_CONDITION,SNOW,UNKNOWN,CLEAR,CLEAR,SNOW
LIGHTING_CONDITION,DAYLIGHT,DAYLIGHT,UNKNOWN,DAYLIGHT,DAYLIGHT
FIRST_CRASH_TYPE,SIDESWIPE SAME DIRECTION,TURNING,PARKED MOTOR VEHICLE,PEDALCYCLIST,REAR END
TRAFFICWAY_TYPE,DIVIDED - W/MEDIAN (NOT RAISED),DIVIDED - W/MEDIAN (NOT RAISED),NOT DIVIDED,NOT DIVIDED,FOUR WAY
ALIGNMENT,STRAIGHT AND LEVEL,STRAIGHT AND LEVEL,STRAIGHT AND LEVEL,STRAIGHT AND LEVEL,STRAIGHT AND LEVEL
ROADWAY_SURFACE_COND,SNOW OR SLUSH,UNKNOWN,DRY,DRY,WET
ROAD_DEFECT,NO DEFECTS,UNKNOWN,NO DEFECTS,NO DEFECTS,NO DEFECTS
REPORT_TYPE,ON SCENE,NOT ON SCENE (DESK REPORT),ON SCENE,ON SCENE,NOT ON SCENE (DESK REPORT)
CRASH_TYPE,NO INJURY / DRIVE AWAY,NO INJURY / DRIVE AWAY,NO INJURY / DRIVE AWAY,INJURY AND / OR TOW DUE TO CRASH,NO INJURY / DRIVE AWAY
DAMAGE,"$501 - $1,500","OVER $1,500","OVER $1,500",$500 OR LESS,"OVER $1,500"
DATE_POLICE_NOTIFIED,01/14/2025 12:38:00 PM,05/27/2025 10:40:00 AM,04/05/2025 09:23:00 PM,05/23/2025 09:16:00 AM,01/14/2025 08:45:00 AM
PRIM_CONTRIBUTORY_CAUSE,IMPROPER TURNING/NO SIGNAL,IMPROPER OVERTAKING/PASSING,UNABLE TO DETERMINE,UNABLE TO DETERMINE,FOLLOWING TOO CLOSELY
SEC_CONTRIBUTORY_CAUSE,IMPROPER OVERTAKING/PASSING,IMPROPER OVERTAKING/PASSING,UNABLE TO DETERMINE,UNABLE TO DETERMINE,FOLLOWING TOO CLOSELY
STREET_NO,6352,3555,1005,2901,4001
STREET_DIRECTION,N,N,N,W,W
STREET_NAME,SHERIDAN RD,WESTERN AVE,DRAKE AVE,DIVISION ST,111TH ST
BEAT_OF_OCCURRENCE,2433.0,1921.0,1121.0,1211.0,2211.0
NUM_UNITS,2,2,2,2,2
MOST_SEVERE_INJURY,NO INDICATION OF INJURY,NO INDICATION OF INJURY,NO INDICATION OF INJURY,NONINCAPACITATING INJURY,NO INDICATION OF INJURY
INJURIES_TOTAL,0.0,0.0,0.0,1.0,0.0
INJURIES_FATAL,0.0,0.0,0.0,0.0,0.0
INJURIES_INCAPACITATING,0.0,0.0,0.0,0.0,0.0
INJURIES_NON_INCAPACITATING,0.0,0.0,0.0,1.0,0.0
INJURIES_REPORTED_NOT_EVIDENT,0.0,0.0,0.0,0.0,0.0
INJURIES_NO_INDICATION,2.0,2.0,1.0,2.0,2.0
INJURIES_UNKNOWN,0.0,0.0,0.0,0.0,0.0
CRASH_HOUR,12,9,20,9,8
CRASH_DAY_OF_WEEK,3,6,7,6,3
CRASH_MONTH,1,5,4,5,1
LATITUDE,41.997808,41.946529,41.899325,41.902793,41.691207
LONGITUDE,-87.65577,-87.688106,-87.715074,-87.699412,-87.720555
LOCATION,POINT (-87.655770494712 41.997807727633),POINT (-87.688106391039 41.946529480518),POINT (-87.715074373867 41.899324573751),POINT (-87.699412181285 41.902792968177),POINT (-87.720554863466 41.691206664451)
date,2025-01-14 12:25:00,2025-05-23 09:30:00,2025-04-05 20:00:00,2025-05-23 09:15:00,2025-01-14 08:00:00
year,2025,2025,2025,2025,2025

In [4]:
df.shape #660934, 39

(660934, 39)

In [5]:
columns = df.columns.to_list()
column_dtypes = df.dtypes.to_list()

In [6]:
for item in zip(columns, column_dtypes):
    print(item)

('CRASH_RECORD_ID', dtype('O'))
('CRASH_DATE', dtype('O'))
('POSTED_SPEED_LIMIT', dtype('int64'))
('TRAFFIC_CONTROL_DEVICE', dtype('O'))
('DEVICE_CONDITION', dtype('O'))
('WEATHER_CONDITION', dtype('O'))
('LIGHTING_CONDITION', dtype('O'))
('FIRST_CRASH_TYPE', dtype('O'))
('TRAFFICWAY_TYPE', dtype('O'))
('ALIGNMENT', dtype('O'))
('ROADWAY_SURFACE_COND', dtype('O'))
('ROAD_DEFECT', dtype('O'))
('REPORT_TYPE', dtype('O'))
('CRASH_TYPE', dtype('O'))
('DAMAGE', dtype('O'))
('DATE_POLICE_NOTIFIED', dtype('O'))
('PRIM_CONTRIBUTORY_CAUSE', dtype('O'))
('SEC_CONTRIBUTORY_CAUSE', dtype('O'))
('STREET_NO', dtype('int64'))
('STREET_DIRECTION', dtype('O'))
('STREET_NAME', dtype('O'))
('BEAT_OF_OCCURRENCE', dtype('float64'))
('NUM_UNITS', dtype('int64'))
('MOST_SEVERE_INJURY', dtype('O'))
('INJURIES_TOTAL', dtype('float64'))
('INJURIES_FATAL', dtype('float64'))
('INJURIES_INCAPACITATING', dtype('float64'))
('INJURIES_NON_INCAPACITATING', dtype('float64'))
('INJURIES_REPORTED_NOT_EVIDENT', dtype('float64'))
('INJURIES_NO_INDICATION', dtype('float64'))
('INJURIES_UNKNOWN', dtype('float64'))
('CRASH_HOUR', dtype('int64'))
('CRASH_DAY_OF_WEEK', dtype('int64'))
('CRASH_MONTH', dtype('int64'))
('LATITUDE', dtype('float64'))
('LONGITUDE', dtype('float64'))
('LOCATION', dtype('O'))
('date', dtype('O'))
('year', dtype('int64'))

In [7]:
df.isnull().sum()

CRASH_RECORD_ID                  0
CRASH_DATE                       0
POSTED_SPEED_LIMIT               0
TRAFFIC_CONTROL_DEVICE           0
DEVICE_CONDITION                 0
WEATHER_CONDITION                0
LIGHTING_CONDITION               0
FIRST_CRASH_TYPE                 0
TRAFFICWAY_TYPE                  0
ALIGNMENT                        0
ROADWAY_SURFACE_COND             0
ROAD_DEFECT                      0
REPORT_TYPE                      0
CRASH_TYPE                       0
DAMAGE                           0
DATE_POLICE_NOTIFIED             0
PRIM_CONTRIBUTORY_CAUSE          0
SEC_CONTRIBUTORY_CAUSE           0
STREET_NO                        0
STREET_DIRECTION                 0
STREET_NAME                      0
BEAT_OF_OCCURRENCE               0
NUM_UNITS                        0
MOST_SEVERE_INJURY               0
INJURIES_TOTAL                   0
INJURIES_FATAL                   0
INJURIES_INCAPACITATING          0
INJURIES_NON_INCAPACITATING      0
INJURIES_REPORTED_NOT_EVIDENT    0
INJURIES_NO_INDICATION           0
INJURIES_UNKNOWN                 0
CRASH_HOUR                       0
CRASH_DAY_OF_WEEK                0
CRASH_MONTH                      0
LATITUDE                         0
LONGITUDE                        0
LOCATION                         0
date                             0
year                             0
dtype: int64

In [12]:
df['CRASH_RECORD_ID'].astype(str).str.len().min() #min, max 128. soo all ids are 128 char long

128

In [14]:
df.tail().T

,660929,660930,660931,660932,660933
CRASH_RECORD_ID,5ff5b050ae2079df6addca8431c1bd6e381432ff72ff43...,7a7963ac15a38f3cf7549397dd053fd7612dd5194de280...,84e546c12fd8fd78ae4e2dc26fdb02d6e8f6c4c92be450...,8237045757e7fed5adfb450bd7c8472e28a61d322f86bb...,ede74fa6fd507334cd0415d3d53deb535d27d23523cd38...
CRASH_DATE,10/18/2025 11:42:00 AM,10/18/2025 03:50:00 AM,10/18/2025 05:08:00 PM,10/19/2025 01:50:00 AM,06/23/2023 04:30:00 PM
POSTED_SPEED_LIMIT,35,35,30,30,30
TRAFFIC_CONTROL_DEVICE,TRAFFIC SIGNAL,NO CONTROLS,NO CONTROLS,UNKNOWN,UNKNOWN
DEVICE_CONDITION,FUNCTIONING PROPERLY,NO CONTROLS,NO CONTROLS,UNKNOWN,UNKNOWN
WEATHER_CONDITION,CLOUDY/OVERCAST,RAIN,CLEAR,UNKNOWN,UNKNOWN
LIGHTING_CONDITION,DAYLIGHT,DARKNESS,DAYLIGHT,UNKNOWN,DAYLIGHT
FIRST_CRASH_TYPE,REAR END,FIXED OBJECT,SIDESWIPE SAME DIRECTION,REAR TO FRONT,REAR END
TRAFFICWAY_TYPE,NOT DIVIDED,NOT DIVIDED,NOT DIVIDED,NOT DIVIDED,NOT DIVIDED
ALIGNMENT,STRAIGHT AND LEVEL,STRAIGHT AND LEVEL,STRAIGHT AND LEVEL,STRAIGHT AND LEVEL,STRAIGHT AND LEVEL
ROADWAY_SURFACE_COND,UNKNOWN,WET,DRY,UNKNOWN,UNKNOWN
ROAD_DEFECT,UNKNOWN,NO DEFECTS,NO DEFECTS,UNKNOWN,UNKNOWN
REPORT_TYPE,ON SCENE,NOT ON SCENE (DESK REPORT),NOT ON SCENE (DESK REPORT),NOT ON SCENE (DESK REPORT),ON SCENE
CRASH_TYPE,INJURY AND / OR TOW DUE TO CRASH,NO INJURY / DRIVE AWAY,NO INJURY / DRIVE AWAY,NO INJURY / DRIVE AWAY,INJURY AND / OR TOW DUE TO CRASH
DAMAGE,"OVER $1,500","OVER $1,500","OVER $1,500","OVER $1,500",$500 OR LESS
DATE_POLICE_NOTIFIED,10/18/2025 11:42:00 AM,10/19/2025 11:30:00 PM,10/19/2025 09:00:00 AM,10/19/2025 02:12:00 AM,07/01/2023 01:15:00 PM
PRIM_CONTRIBUTORY_CAUSE,FAILING TO REDUCE SPEED TO AVOID CRASH,WEATHER,UNABLE TO DETERMINE,IMPROPER BACKING,FOLLOWING TOO CLOSELY
SEC_CONTRIBUTORY_CAUSE,FAILING TO REDUCE SPEED TO AVOID CRASH,WEATHER,UNABLE TO DETERMINE,NOT APPLICABLE,FOLLOWING TOO CLOSELY
STREET_NO,3231,898,2416,3700,6799
STREET_DIRECTION,N,N,S,N,N
STREET_NAME,CUMBERLAND AVE,LAKE SHORE DR,DAMEN AVE,BROADWAY,KEDZIE AVE
BEAT_OF_OCCURRENCE,1631.0,1833.0,1034.0,1925.0,2412.0
NUM_UNITS,3,1,2,2,2
MOST_SEVERE_INJURY,"REPORTED, NOT EVIDENT",NO INDICATION OF INJURY,NO INDICATION OF INJURY,NO INDICATION OF INJURY,INCAPACITATING INJURY
INJURIES_TOTAL,2.0,0.0,0.0,0.0,1.0
INJURIES_FATAL,0.0,0.0,0.0,0.0,0.0
INJURIES_INCAPACITATING,0.0,0.0,0.0,0.0,1.0
INJURIES_NON_INCAPACITATING,0.0,0.0,0.0,0.0,0.0
INJURIES_REPORTED_NOT_EVIDENT,2.0,0.0,0.0,0.0,0.0
INJURIES_NO_INDICATION,1.0,1.0,5.0,5.0,1.0
INJURIES_UNKNOWN,0.0,0.0,0.0,0.0,0.0
CRASH_HOUR,11,3,17,1,16
CRASH_DAY_OF_WEEK,7,7,7,1,6
CRASH_MONTH,10,10,10,10,6
LATITUDE,41.938537,41.8992,41.848081,41.949157,42.004564
LONGITUDE,-87.835965,-87.618841,-87.675881,-87.648527,-87.7092
LOCATION,POINT (-87.835965097138 41.938536628877),POINT (-87.618840672611 41.8992002546),POINT (-87.675881338024 41.848080595588),POINT (-87.648526617888 41.949157243366),POINT (-87.709200383599 42.004564031467)
date,2025-10-18 11:42:00,2025-10-18 03:50:00,2025-10-18 17:08:00,2025-10-19 01:50:00,2023-06-23 16:30:00
year,2025,2025,2025,2025,2023

In [15]:
df[['CRASH_DATE','date']].head(10).T

,0,1,2,3,4,5,6,7,8,9
CRASH_DATE,01/14/2025 12:25:00 PM,05/23/2025 09:30:00 AM,04/05/2025 08:00:00 PM,05/23/2025 09:15:00 AM,01/14/2025 08:00:00 AM,01/14/2025 01:44:00 PM,03/16/2025 11:22:00 PM,12/04/2024 08:27:00 AM,10/05/2024 03:45:00 AM,09/07/2024 10:10:00 PM
date,2025-01-14 12:25:00,2025-05-23 09:30:00,2025-04-05 20:00:00,2025-05-23 09:15:00,2025-01-14 08:00:00,2025-01-14 13:44:00,2025-03-16 23:22:00,2024-12-04 08:27:00,2024-10-05 03:45:00,2024-09-07 22:10:00

In [22]:
df['TRAFFIC_CONTROL_DEVICE'].astype(str).str.len().max() #max 24, min 5

24

In [23]:
df['DEVICE_CONDITION'].astype(str).str.len().max() #max 24, min 5

24

In [43]:
for col in columns:
    print(col,end=" ")
    print(df[col].astype(str).str.len().max())

CRASH_RECORD_ID 128
CRASH_DATE 22
POSTED_SPEED_LIMIT 2
TRAFFIC_CONTROL_DEVICE 24
DEVICE_CONDITION 24
WEATHER_CONDITION 24
LIGHTING_CONDITION 22
FIRST_CRASH_TYPE 28
TRAFFICWAY_TYPE 31
ALIGNMENT 21
ROADWAY_SURFACE_COND 15
ROAD_DEFECT 17
REPORT_TYPE 26
CRASH_TYPE 32
DAMAGE 13
DATE_POLICE_NOTIFIED 22
PRIM_CONTRIBUTORY_CAUSE 80
SEC_CONTRIBUTORY_CAUSE 80
STREET_NO 5
STREET_DIRECTION 1
STREET_NAME 27
BEAT_OF_OCCURRENCE 6
NUM_UNITS 2
MOST_SEVERE_INJURY 24
INJURIES_TOTAL 4
INJURIES_FATAL 3
INJURIES_INCAPACITATING 4
INJURIES_NON_INCAPACITATING 4
INJURIES_REPORTED_NOT_EVIDENT 4
INJURIES_NO_INDICATION 4
INJURIES_UNKNOWN 3
CRASH_HOUR 2
CRASH_DAY_OF_WEEK 1
CRASH_MONTH 2
LATITUDE 13
LONGITUDE 14
LOCATION 40
date 19
year 4

In [44]:
df.dtypes

CRASH_RECORD_ID                   object
CRASH_DATE                        object
POSTED_SPEED_LIMIT                 int64
TRAFFIC_CONTROL_DEVICE            object
DEVICE_CONDITION                  object
WEATHER_CONDITION                 object
LIGHTING_CONDITION                object
FIRST_CRASH_TYPE                  object
TRAFFICWAY_TYPE                   object
ALIGNMENT                         object
ROADWAY_SURFACE_COND              object
ROAD_DEFECT                       object
REPORT_TYPE                       object
CRASH_TYPE                        object
DAMAGE                            object
DATE_POLICE_NOTIFIED              object
PRIM_CONTRIBUTORY_CAUSE           object
SEC_CONTRIBUTORY_CAUSE            object
STREET_NO                          int64
STREET_DIRECTION                  object
STREET_NAME                       object
BEAT_OF_OCCURRENCE               float64
NUM_UNITS                          int64
MOST_SEVERE_INJURY                object
INJURIES_TOTAL                   float64
INJURIES_FATAL                   float64
INJURIES_INCAPACITATING          float64
INJURIES_NON_INCAPACITATING      float64
INJURIES_REPORTED_NOT_EVIDENT    float64
INJURIES_NO_INDICATION           float64
INJURIES_UNKNOWN                 float64
CRASH_HOUR                         int64
CRASH_DAY_OF_WEEK                  int64
CRASH_MONTH                        int64
LATITUDE                         float64
LONGITUDE                        float64
LOCATION                          object
date                              object
year                               int64
dtype: object